// German words of the Betrieb area. Moves into the dictionary (src/i18n) once
// the Leitstand mount lands.
export const T = {
  queue: "Warteschlange",
  queueEmpty: "Warteschlange leer",
  queueEmptyHint: "Sobald eine Aufgabe eingereiht ist, erscheint sie hier.",
  queueOffline: "Warteschlange nicht lesbar",
  queueOfflineHint: "Der Kern antwortet gerade nicht.",
  loading: "Wird gelesen …",
  statusQueued: "Wartet",
  statusSharpening: "Schärft",
  statusReady: "Bereit",
  statusDispatching: "Startet",
  autoProfile: "Auto",
  check: "Startprüfung",
  slots: "Freie Worker-Slots",
  slotsOffline: "Freie Worker-Slots noch nicht verbunden",
  slotsHint: "Die Oberfläche bekommt diese Angabe noch nicht vom Kern.",
  ram: "Arbeitsspeicher",
  ramOffline: "Arbeitsspeicher noch nicht verbunden",
  ramHint: "Der Kern liefert gerade keinen Wert.",
  ramOfApp: "Arbeitsspeicher der App",
  gigabytes: (n: string) => `${n} GB`,
  ramOf: (used: string, total: string) => `${used} von ${total}`,
  watchdog: "Wachhund",
  watchdogOffline: "Wachhund noch nicht verbunden",
  watchdogHint: "Der Kern ist fertig, die Anbindung fehlt noch.",
  watchdogRef: "V2-B22 (Kern gemergt, noch nicht verdrahtet)",
} as const;
